### ISSUE TITLE
 Atari-BASIC-benchmarks/scruss is not comparable to bench64.bas

### ISSUE THREAD

**Issue by scruss** [maurymarkowitz/Atari-BASIC-benchmarks#1]
Hi, I see that this claims to be comparable to [bench64](https://github.com/scruss/bench64). It clearly isn't:

* `LET` isn't used to define variables throughout
* There are lines with multiple statements per line
* Without `DEF FN`, you're testing something else entirely.

I'd like it if you removed my name from this code, please, as it is contrary to the intention of what I wrote

**Comment by maurymarkowitz** [comment]
All fixed.

BTW, you don't have to define variables in AB, that happens at edit time.
